Repository hoprnet/hopr-core-connector-interface, pull requests merged in 2020-08, with the labels that each got.

#28 Node version
  .github/workflows/nodejs.yml
  package.json
Labels: merge when passing

#29 bump patch version
  package.json
Labels: Patch Version, merge when passing

#32 add public key to interface
  src/types/index.d.ts
  src/types/public.d.ts
Labels: Patch Version

#34 fixed indexer types
  src/channel.d.ts
  src/indexer.d.ts
  src/utils.d.ts
Labels: Minor Version

#35 public can be undefined
  src/types/channel.d.ts
  src/types/ticket.d.ts
Labels: Patch Version

#36 integrate path finder
  .npmignore
  package.json
  src/index.d.ts
  src/index.spec.ts
  src/path.d.ts
  tsconfig.json
  yarn.lock
Labels: Patch Version

#37 Feature/add constructors
  .npmignore
  src/types/accountId.d.ts
  src/types/balance.d.ts
  src/types/hash.d.ts
  src/types/moment.d.ts
  src/types/nativeBalance.d.ts
  src/types/public.d.ts
  src/types/state.d.ts
  src/types/ticketEpoch.d.ts
Labels: Patch Version

#38 proper constructor declarations
  src/channel.d.ts
  src/index.d.ts
  src/types/accountId.d.ts
  src/types/balance.d.ts
  src/types/channel.d.ts
  src/types/channelBalance.d.ts
  src/types/hash.d.ts
  src/types/moment.d.ts
  src/types/nativeBalance.d.ts
  src/types/public.d.ts
  src/types/signature.d.ts
  src/types/signedChannel.d.ts
  src/types/signedTicket.d.ts
  src/types/state.d.ts
  src/types/ticket.d.ts
  src/types/ticketEpoch.d.ts
Labels: Patch Version

#39 make toU8a() mandatory
  .gitignore
  src/types/balance.d.ts
  src/types/moment.d.ts
  src/types/nativeBalance.d.ts
Labels: Patch Version

#40 upgrade path selection api
  src/index.d.ts
  src/path.d.ts
  src/pathSelection.d.ts
Labels: Patch Version
